furniture:
  general:
    max_face: 32
    max_edge: 30
    edge_classes: 5
  datasets:


  model:
    n_layer: 5
    d_model: 256

deepcad:
  general:
    max_face: 30
    max_edge: 200
  model:
    n_layer: 4
    d_model: 128

abc:
  general:
    max_face: 200
    max_edge: 400
  model:
    n_layer: 6
    d_model: 512